Support reading and storing ReplayGain metadata
fooyin/fooyin pull request #251
Opened 2024-08-31 19:59 UTC by lstrsrt

We don't do anything with these fields yet and they don't show up in the property viewer, but at least they're in the database now. This is step 1 towards resolving #129. Applying these fields in the playback engine should be pretty simple. I'll see what I can do tomorrow.

2024-08-31 20:06 UTC, lstrsrt commented
Oops, will fix the build in a second.

I also investigated calculating ReplayGain values. The math looks difficult and highly error-prone so I think pulling in libebur128 might be a better idea than writing the code. It could also be an optional dependency, so when it's not available we just don't give the user the option to calculate RG values.

2024-09-01 06:01 UTC, diizzyy commented
This can be done by using FFmpeg ( https://github.com/cyanreg/cyanrip/commit/5285205fda8812a07d3f056a336517c094181e39 ) which would be nice to avoid external dependencies.

2024-09-01 06:09 UTC, lstrsrt commented
I see, thanks. Somehow didn't see that comment about ffmpeg.

2024-09-02 09:48 UTC, ludouzi requested changes

2024-09-02 09:48 UTC, ludouzi commented on src/core/engine/taglibparser.cpp
> +            return string.chopped(2).toDouble();
Clang-tidy gives a `bugprone-narrowing-conversions` warning here. You'll need to cast it or just use QString::toFloat.

2024-09-02 09:50 UTC, ludouzi commented
Thanks for making a start on this.

The fields were actually already stored as strings in the database in the extra tags blob, though it makes sense to store them in their own columns.

I agree with @diizzyy that we should avoid bringing in another dependency if possible. Or make it a plugin if not.

2024-09-02 09:55 UTC, lstrsrt commented on src/core/engine/taglibparser.cpp
> +            return string.chopped(2).toDouble();
Oh yeah, I was using a double for these values earlier and forgot to convert all the function calls, thanks. There's also an "if" on line 670 that should be an "else if" which I'll change as well.

2024-09-02 10:03 UTC, lstrsrt commented
If ffmpeg can be used for this there's definitely no need for a new dependency.

Does this change also warrant a database reload message?

2024-09-02 10:22 UTC, ludouzi commented
> Does this change also warrant a database reload message?

It will yeah so the replaygain data in the extra tags blob is removed.

2024-09-02 10:38 UTC, lstrsrt commented
Done 👍

2024-09-02 10:54 UTC, ludouzi approved these changes

2024-09-02 10:54 UTC, merged